project:
  type: website
  output-dir: _site
  preview:
    port: 5896
    browser: false
  render:
    - "*.qmd"
    - "!fragments"
  resources:
    - "parts"
    - "examples.zip"

website:
  title: "surveydown workshop"
  image: images/logo.ico
  favicon: images/logo.ico
  site-url: https://jhelvy.github.io/2025-surveydown-workshop/
  repo-url: https://github.com/jhelvy/2025-surveydown-workshop/
  description: 'Content for my 2025 workshop on building surveys with surveydown.'
  search: false
  open-graph:
    locale: es_ES
    site-name: https://surveydown.org
  twitter-card:
    creator: "@johnhelveston"
    site: "@johnhelveston"
    image: logo.png
    card-style: summary_large_image
    image-width: 150
    image-height: 150
  navbar:
    background: primary
    search: true
    left:
      - text: Home
        icon: house-door-fill
        href: index.html
      - text: Install
        icon: tools
        href: install.html
      - text: Examples
        icon: download
        href: examples.zip
      - text: Parts
        icon: puzzle-fill
        menu: 
        - text: Getting Started
          href: parts/getting-started.html
        - text: Conditional Control
          href: parts/conditional-control.html
        - text: Data Handling
          href: parts/data-handling.html
        - text: Reactivity
          href: parts/reactivity.html
    right:
      - icon: github
        href: https://github.com/jhelvy/2025-surveydown-workshop

  page-footer:
    background: dark
    center:
      - text: "Workshop on building surveys with surveydown (Spring 2025)<br><a href='https://www.jhelvy.com'><i class='fas fa-user'></i> Dr. John Paul Helveston</a> | <a href='mailto:jph@gwu.edu'><i class='fas fa-envelope'></i> jph@gwu.edu</a> | <a href='https://github.com/jhelvy/2025-surveydown-workshop'><i class='fa fa-github'></i></a> | <a href='https://bsky.app/profile/jhelvy.bsky.social'><i class='fa fa-brands fa-bluesky'></i></a><br><a href='LICENSE.html'>LICENSE: CC-BY-SA <i class='fab fa-creative-commons'></i><i class='fab fa-creative-commons-by'></i><i class='fab fa-creative-commons-sa'></i></a>"

format:
  html:
    theme: [flatly, theme.scss]
    css: styles.css
    anchor-sections: true
    smooth-scroll: true
    link-external-newwindow: true
    include-in-header: "_includes/header.html"

code-link: true
knitr:
  opts_chunk:
    comment: "#>"
fig-retina: 3
